### ISSUE TITLE
关于项目的疑问

### ISSUE THREAD

**Issue by PrayerT** [whoiswennie/AI-Vtuber#1]
ReadMe中能否简述一下项目的作用以及场景？比如输入输出，适用哪些直播平台，可以参照：
https://github.com/0x648/luna-ai
提个建议，因为点进来不知道这个项目能做到什么，有些疑惑

**Comment by whoiswennie** [comment]
> ReadMe中能否简述一下项目的作用以及场景？比如输入输出，适用哪些直播平台，可以参照： https://github.com/0x648/luna-ai 提个建议，因为点进来不知道这个项目能做到什么，有些疑惑

好的，因为目前项目正在重构和实验新功能所以就简单写了下readme，这两天就加上。
